POST http://127.0.0.1:8000/signup
Content-Type: application/json

{
    "username":"john", 
    "password":"jjjjjj",
    "email":"john@mail.com"
}
###
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "email":"a@mail.com", 
    "password":"aaaaaa"
}
###
GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: token 9a644d20d212a03541d8378747d7f6f6c1197b02

{
  
}

### POST /api/justify
POST http://127.0.0.1:8000/justify/
Content-Type: text/plain
Authorization: token 2c74f1ff8345545be2113fef92bc449dc4107de7

